ISO2CNT = {
    "AP": "ARIPO",
    "AM": "ARMENIA",
    "DZ": "Algeria",
    "AR": "Argentina",
    "AU": "Australia",
    "AT": "Austria",
    "BY": "Belarus",
    "BE": "Belgium",
    "BA": "Bosnia and Herzegovina",
    "BR": "Brazil",
    "BG": "Bulgaria",
    "CA": "Canada",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "GC": "Cooperation Council for the Arab states of the Gulf",
    "CR": "Costa Rica",
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "CS": "Czechoslovakia",
    "DK": "Denmark",
    "DO": "Dominican Republic",
    "EM": "EUIPO",
    "MO": "Macau",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "EE": "Estonia",
    "EA": "Eurasian Patent Office",
    "EP": "European Patent Office",
    "FI": "Finland",
    "FR": "France",
    "GE": "Georgia",
    "DD": "German Democratic Republic",
    "DE": "Germany",
    "GR": "Greece",
    "GT": "Guatemala",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IT": "Italy",
    "JP": "Japan",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "LV": "Latvia",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MW": "MALAWI",
    "MY": "Malaysia",
    "MT": "Malta",
    "MX": "Mexico",
    "MD": "Moldova",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MA": "Morocco",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NO": "Norway",
    "OA": "OAPI",
    "PA": "Panama",
    "PE": "Peru",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "RU": "Russia",
    "SM": "San Marino",
    "SA": "Saudi Arabia",
    "RS": "Serbia",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "ZA": "South Africa",
    "KR": "South Korea",
    "ES": "Spain",
    "SE": "Sweden",
    "CH": "Switzerland",
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TH": "Thailand",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "SU": "USSR - Soviet Union",
    "UA": "Ukraine",
    "GB": "United Kingdom",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VN": "Vietnam",
    "WO": "WIPO (PCT)",
    "YU": "Yugoslavia",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
}

CNT_GROUPS = {
    "english_speaking": [
        "AP",
        "AU",
        "CA",
        "EA",
        "EP",
        "GB",
        "HK",
        "IE",
        "IN",
        "NZ",
        "SG",
        "US",
        "ZA",
    ],
    "g7": ["CA", "FR", "DE", "IT", "JP", "GB", "US"],
    "brics": ["BR", "RU", "IN", "CN", "ZA"],
}
