patent:
  zinc finger: WO-2000041566-A9,WO-2003087341-A3
  talens: WO-2010079430-A1,WO-2011072246-A2,US-8440431-B2,US-8440432-B2,US-8450471-B2,US-8566363-B2
  crispr: WO-2014093661-A2,WO-2013176772-A1
  others: US-20170367280-A1
cpc:
  general:  A01H4/00;A01K67/00,C12N/1500,C12N1/00,C12N5/00,C12N7/00C12Y,C12N5/10,C12Q1/68,C12Q1/70,G01N33/00,A61K48/00,A61K31/7088,C07K14/00
keyword:
  general: dna editing,gene editing,genome engineering,recombinant targeting vectors,homologous recombination,double-strand dna break,homology-directed repair,targeted dna sequence,dna cleavage,fok1,sequence-specific nuclease system
  zinc finger: zinc finger nuclease,cys2-his2
  talens: transcriptional activator-like effector nuclease,talens
  crispr: clustered regularly interspaced short palindromic repeat,crispr/cas,cas9,pre-crrna,tracrrna,enzyme rnase,single guide rna,crispr-cpf1
  others: ngago,single-stranded dna-guided argonaute endonuclease,natronobacterium gregoriy argonaute