patent:
  text classification: CN-101587493-B,US-7016895-B2
  named entity recognition: US-20150286629-A1,EP-2400401-A3
  question answering: US-20130262501-A1,US-7844598-B2,US-20150026106-A1,US-20160103884-A1,US-20140365502-A1
  language modeling: US-7103544-B2,WO-2004100126-A3,WO-2002054033-A2,JP-4818683-B2,US-20050256715-A1
  summarization: US-20060206806-A1,US-20140195897-A1,US-7752204-B2
  automatic translation: US-5615301-A,US-10452787-B2
cpc:
  natural language processing: G06F17/27,G06F17/28,H04L41/16,G06F17/289,G06F17/2795
keyword:
  general ai - algorithm: adaboost,xgboost,bayesian network,decision tree,genetic algorithm,gradient tree boosting,logistic regression,random forest,rankboost,support vector machine,multilayer perceptron,hidden markov model,generalized adversarial network,convolutional neural network
  general ai - technique: backpropagation,stochastic gradient descent,hashmap
  general ai - concept: supervised training,reinforcement learning,neural network,self learning,semi supervised learning,unsupervised training,transfer learning,overfitting,active learning,clustering,data mining,deep learning,expert system,embedding,machine learning,fuzzy logic,feature selection,objective function,target function,regression model,signal processing
  general nlp: natural language processing,computational linguistics,chatbot,text embedding
  text classification: text classification, sentiment analysis
  named entity recognition: named entity recognition,entity identification,entity chunking,entity extraction
  question answering: automated question answering,automatic question answering
  language modeling: language modeling,bert,gpt-3,gpt-2,word2vec,sense2vec,recursive neural network,sequence modeling
  summarization: text summarization, sentence summary
  automatic translation: automatic translation, machine translation, auto-translate
option:
  - Process natural language
  - Analyse natural language
  - Understand natural language