data:
  train:
  test:

tok2vec:
  max_length: 250
  top_k: 5000

model:
  architecture: cnn
  blocks: 2
  filters: 64
  dropout_rate: .2
  embedding_dim: 100
  kernel_size: 5
  pool_size: 3
  use_pretrained_embedding: False
  is_embedding_trainable: False
  optimizer:
    learning_rate: 1e-3
    loss: binary_crossentropy
    metrics: [ "accuracy" ]

training:
  epochs: 100
  batch_size: 64
  callbacks:
    monitor: val_loss
    patience: 2

logger:
    verbose: 2
