model:
  architecture: cnn

data prep:
  max_length: 250
  top_k: 5000

training:
  learning_rate: [1e-3]
  epochs: [100]
  batch_size: [64]
  blocks: [1, 2, 3]
  filters: [64, 128]
  dropout_rate: [0, 0.2]
  embedding_dim: [100]
  kernel_size: [3, 5, 7]
  pool_size: [3]